### ISSUE TITLE
unclear if can obfuscate the set of files in a package

### ISSUE THREAD

**Issue by kwatsen** [Cobertos/bobskater#1]
The code appears to obfuscate files independently, which seems that it might result in mismatched names across files.  If true, please add to `Current limitations`.

**Comment by Cobertos** [comment]
It will obfuscate files independently, but it shouldn't be modifying anything that can exist across files.

From the README.md:
```
`obfuscateNames` will obfuscate all names except globally scoped variables, kwargs, builtins, and identifiers in a class namespace. Defaults to True
```

Everything accessible from externally (globally scoped variables, kwargs, builtins, and identifiers) are all left as is. I had tested this on a large project with file interdependencies 2 years ago and it worked for that one. Support for obfuscating these was something I eventually wanted to add support for eventually (keeping the state of these names between files) but it's not there right now.
