### ISSUE TITLE
unclear if compatible with setup.py entry point

### ISSUE THREAD

**Issue by kwatsen** [Cobertos/bobskater#2]
Related to #1, how can a setup.py entry point call into the obfuscated code?

Assuming the code is obfuscated dynamically when built, how can the obfuscated name of the entry point be determined?

**Comment by Cobertos** [comment]
From my comment in #1 , `bobskater` shouldn't obfuscate "globally scoped variables, kwargs, builtins, and identifiers". In the case of a `setup.py` (example from another project):

```
from setuptools import setup

setup(
    name='unitypackage_extractor',
    version='0.5.1',
    description='Extractor for .unitypackage files',
    long_description=open('README.md', 'r').read(),
    long_description_content_type="text/markdown",
    url='https://github.com/Cobertos/unitypackage_extractor/',
    author='Cobertos',
    author_email='me@cobertos.com',
    license='MIT',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Topic :: Software Development :: Build Tools',
        'Topic :: System :: Filesystems'
    ],
    keywords='untiy unity3d unitypackage extract tar extractor',
    packages=['unitypackage_extractor']
)
```

everything in here would be untouched and you should get the same file out as you put in. `setup` is a global variable, so wouldn't be obfuscated. `name`, `version`, `description`, etc are all `kwargs` and also won't be obfuscated (as it needs to stay the same name for API interoperability).

If the `setup.py` you're obfuscating has things obfuscated that shouldn't be, it would be a bug.

**Comment by kwatsen** [comment]
Sorry for not being clear.  My intention is not to obfuscate the `setup.py` file itself, but rather trying to understand if the console script generated by `setup.py` will be able to access the entry point in the obfuscated code.  For instance, see the **last line** below:

```
setup(
    <SNIP>
    entry_points = { "console_scripts": ["PKG_NAME=PKG_NAME.__main__:main"] }
)
```
If I understand your previous response, nether the module name (`__main__`) nor function name (`main`) will be obfuscated.  Is that correct?   [I guess I'll find out shortly, but your confirmation would be reassuring]

BTW, have you ever created a `setup.py` script to automatically obfuscate when generating an sdist, egg, or wheel?

**Comment by Cobertos** [comment]
You are correct in your reasoning, yes.

I have not done it in a `setup.py` but I had a CI script that I had it bundled with for another application. I can get that snippet in a few hours.

**Comment by Cobertos** [comment]
Here was the minification/obfuscation step of that build

```python
    print("Minifier/Obfuscation...")
    for file in glob.glob(distDir + "/**/*.py", recursive=True):
        #Obfuscate the file source
        print(file + ": Obfuscating... ", end='')
        obfuscateFile(file, obfuscateNames=obfuscate)

        #Compile it to a .pyc (very small compilation benefit)
        #cfile = file[:-2] + "pyc"
        #print("Compiling " + file + " to " + cfile)
        #compile(file, cfile=cfile, optimize=2)
        #os.remove(file)

        #Add copyright comments to the top of the file
        print("Copyright Header...")
        transformFile(file, lambda s: copyrightHeader + s)
```
